### ISSUE TITLE
Fetching `Attribute(..., ctx=Store())` failed for some python versions

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/executing#39]
Script to test:

```python
import sys
import ast
import executing

print("")
print("-" * 80)
print(sys.version)

class Foo:

    def __setattr__(self, name, value) -> None:
        # print(argname("name", vars_only=True))
        node = executing.Source.executing(sys._getframe(1)).node
        print(ast.dump(node))

f = Foo()

f.x = 1
```

```
❯ for i in py36 py37 py38 py3_9_10 py310; conda run -n $i --no-capture-output python test.py; end  
                             
--------------------------------------------------------------------------------
3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41) 
[GCC 9.4.0]
Attribute(value=Name(id='f', ctx=Load()), attr='x', ctx=Store())

--------------------------------------------------------------------------------
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    f.x = 1
  File "test.py", line 13, in __setattr__
    print(ast.dump(node))
  File "/home/pwwang/miniconda3/envs/py37/lib/python3.7/ast.py", line 120, in dump
    raise TypeError('expected AST, got %r' % node.__class__.__name__)
TypeError: expected AST, got 'NoneType'

--------------------------------------------------------------------------------
3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
Attribute(value=Name(id='f', ctx=Load()), attr='x', ctx=Store())

--------------------------------------------------------------------------------
3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37) 
[GCC 9.4.0]
Traceback (most recent call last):
  File "/home/pwwang/github/python-varname/test.py", line 17, in <module>
    f.x = 1
  File "/home/pwwang/github/python-varname/test.py", line 13, in __setattr__
    print(ast.dump(node))
  File "/home/pwwang/miniconda3/envs/py3_9_10/lib/python3.9/ast.py", line 169, in dump
    raise TypeError('expected AST, got %r' % node.__class__.__name__)
TypeError: expected AST, got 'NoneType'

--------------------------------------------------------------------------------
3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Traceback (most recent call last):
  File "/home/pwwang/github/python-varname/test.py", line 17, in <module>
    f.x = 1
  File "/home/pwwang/github/python-varname/test.py", line 13, in __setattr__
    print(ast.dump(node))
  File "/home/pwwang/miniconda3/envs/py310/lib/python3.10/ast.py", line 172, in dump
    raise TypeError('expected AST, got %r' % node.__class__.__name__)
TypeError: expected AST, got 'NoneType'
```

Looks like only python 3.6 and 3.8 worked.

`__setitem__()` behaved the same.

**Comment by alexmojaki** [comment]
Add a `print(executing.__version__)`. For me it failed on some versions of Python but only before I upgraded `executing` for those versions.

**Comment by alexmojaki** [comment]
Also, this code will make it raise the original exception instead of setting the node to None:

```python
import executing.executing

executing.executing.TESTING = 1
```

**Comment by pwwang** [comment]
> Add a `print(executing.__version__)`. For me it failed on some versions of Python but only before I upgraded `executing` for those versions.

Ah, that's the case for me as well.
